name: NodeJS CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Run npm test with secrets
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
        SECRET_JWT: ${{ secrets.SECRET_JWT }}
      run: npm run test-ci
    - run: npm start &
